/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package test;
import modelo.*;
import gestion.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Average
 */
public class PartidosPoliticos extends javax.swing.JPanel {
    private GestionPartido gestionPartido;
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form PartidosPoliticos
     */
    public PartidosPoliticos() {
        initComponents();
        gestionPartido= new GestionPartido();
        
    }
    public PartidosPoliticos(GestionPartido gestionPartido) {
        initComponents();
        this.gestionPartido= gestionPartido;
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Nombre del Partido Politico");
        modeloTabla.addColumn("Siglas");
        modeloTabla.addColumn("Logo");
        modeloTabla.addColumn("Representante Legal");
        
        taListaPartidos.setModel(modeloTabla);
        actualizarTabla();
    }
    //Metodos Privados
    private void limpiarTabla(){
        for (int i = modeloTabla.getRowCount()-1; i >= 0 ; i--) {
            modeloTabla.removeRow(i);
            
        }
    }
    private void actualizarTabla(){
        for (int i = 0; i < gestionPartido.longitud(); i++) {
            PartidoPolitico obj = gestionPartido.iesimo(i);
            String[] fila = new String[4];
            fila[0] = obj.getNombrePartido();
            fila[1] = obj.getSigla();
            fila[2] = obj.getLogo();
            fila[3] = obj.getRepresentanteLegal();
            modeloTabla.addRow(fila);
                    
            
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JbtnRegistrar = new javax.swing.JButton();
        JtfNombrePartido = new javax.swing.JTextField();
        JtfSiglas = new javax.swing.JTextField();
        JlNombrePartido = new javax.swing.JLabel();
        JlSiglas = new javax.swing.JLabel();
        JlRepresentanteLegal = new javax.swing.JLabel();
        JtfRepresentanteLegal = new javax.swing.JTextField();
        JlLogo = new javax.swing.JLabel();
        JtfLogo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taListaPartidos = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(102, 0, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Registrar Partidos Politicos");

        JbtnRegistrar.setText("Registrar");
        JbtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnRegistrarActionPerformed(evt);
            }
        });

        JtfNombrePartido.setText("nombre del partido...");
        JtfNombrePartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfNombrePartidoActionPerformed(evt);
            }
        });

        JtfSiglas.setText("siglas....");
        JtfSiglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfSiglasActionPerformed(evt);
            }
        });

        JlNombrePartido.setText("Nombre del Partido Politico: ");

        JlSiglas.setText("Siglas:");

        JlRepresentanteLegal.setText("Representante Legal: ");

        JtfRepresentanteLegal.setText("Representante");

        JlLogo.setText("Logo :  ");

        JtfLogo.setText("logo...");
        JtfLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfLogoActionPerformed(evt);
            }
        });

        taListaPartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(taListaPartidos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JtfNombrePartido, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JlNombrePartido)
                            .addComponent(JlLogo)
                            .addComponent(JtfLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JlRepresentanteLegal)
                            .addComponent(JtfRepresentanteLegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JlSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtfSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JbtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JlNombrePartido)
                            .addComponent(JlSiglas))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JtfSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtfNombrePartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JlRepresentanteLegal)
                            .addComponent(JlLogo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JtfRepresentanteLegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtfLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(JbtnRegistrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnRegistrarActionPerformed
        // TODO add your handling code here:
        
        String nombre = JtfNombrePartido.getText();
        String sigla = JtfSiglas.getText();
        String logo = JtfLogo.getText();
        String representante = JtfRepresentanteLegal.getText();
        PartidoPolitico objP = new  PartidoPolitico(nombre,sigla,logo,representante);
        gestionPartido.agregar(objP);
        JtfNombrePartido.setText("");
        JtfLogo.setText("");
        JtfSiglas.setText("");
        JtfRepresentanteLegal.setText("");
        actualizarTabla();
        
    }//GEN-LAST:event_JbtnRegistrarActionPerformed

    private void JtfNombrePartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfNombrePartidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfNombrePartidoActionPerformed

    private void JtfSiglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfSiglasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfSiglasActionPerformed

    private void JtfLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfLogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfLogoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnRegistrar;
    private javax.swing.JLabel JlLogo;
    private javax.swing.JLabel JlNombrePartido;
    private javax.swing.JLabel JlRepresentanteLegal;
    private javax.swing.JLabel JlSiglas;
    private javax.swing.JTextField JtfLogo;
    private javax.swing.JTextField JtfNombrePartido;
    private javax.swing.JTextField JtfRepresentanteLegal;
    private javax.swing.JTextField JtfSiglas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable taListaPartidos;
    // End of variables declaration//GEN-END:variables
}
